# Use an official Golang runtime as a parent image
FROM golang:1.17-alpine

# Set the working directory to /app
WORKDIR /app

COPY go.mod /app
COPY go.sum /app
# Download and install any required dependencies
RUN go mod download

# Copy the current directory contents into the container at /app
COPY . /app


# Build the Go app
RUN go build -o main .

# Expose port 8080 to the outside world
EXPOSE 8000

# Run the executable
CMD ["./main", "node"]
